###
GET http://localhost:8088/api/authors

###
GET http://localhost:8088/api/authors/1

###
POST http://localhost:8088/api/authors
Content-Type: application/json

< post_request_body.json

###
PUT http://localhost:8088/api/authors
Content-Type: application/json

< put_request_body.json

###
DELETE http://localhost:8088/api/authors/2