version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - spring-boot-rest-mysql-network
    environment:
      - MYSQL_PASSWORD=9109
      - MYSQL_DATABASE=library
      - MYSQL_USER=root
    ports:
      - 3310:3306

  app:
    image: library
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - spring-boot-rest-mysql-network
    restart: unless-stopped
    ports:
      - 8088:8088
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/library?useUnicode=true&serverTimezone=UTC
    depends_on:
      - db

networks:
  spring-boot-rest-mysql-network:
    driver: bridge