version: '3'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web
    environment:
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=library
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3.10.6-management-alpine
    restart: unless-stopped
    networks:
      - web
    ports:
      - 5672:5672
      - 15672:15672

  app:
    image: library
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - web
    restart: unless-stopped
    ports:
      - 8088:8088
    depends_on:
      - db
      - rabbitmq
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

volumes:
  db_data: {}

networks:
  web:
    driver: bridge