version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - web
    environment:
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=library
      - MYSQL_USER=root
    ports:
      - 3306:3306

  app:
    image: library
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - web
    restart: unless-stopped
    ports:
      - 8088:8088
    depends_on:
      - db

networks:
  web:
    driver: bridge