spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://db:3306/library?useUnicode=true&serverTimezone=UTC&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver