server:
  port: 8088

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/library?useUnicode=true&serverTimezone=UTC}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:9109}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml

jwt:
  token:
    secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:JudgeNotAndYouWillNotBeJudged}"'
    expired: 3600000